<!--$sitebuilder version="2.8.5" extra="Java(1.7.0_09)" md5="760efc057f232b654e25b07e80710de2"$-->
<!--$templateKey Generic|Dusk - Indigo|1.0$-->
<html>
  <head>
    <title>Instructors</title>
    <meta name="generator" content="Yahoo! SiteBuilder/2.8.5/1.7.0_09">
    <meta name="description" content="Instructor biographical information for Dominion Shotokan Karate Club, LLC">
    <meta name="keywords" content="Shotokan, karate, instructors">
    <!--$page size 1000, 3000$-->
    <!--$page margin 0, 1, 20, 1$-->
    <!--$centered$-->
    <!--$fontFamily Arial$-->
    <!--$fontSize 12$-->
    <style type="text/css"><!--
      BODY {font-family:"Arial"; font-size:12;margin:0px;padding:0px;text-align:center;min-width:1000px;}
      P {font-family:"Arial"; font-size:12;}
      FORM {margin:0;padding:0;}
      #centerwrapper {text-align:left;width:1000px;margin-left:auto;margin-right:auto;}
    --></style>
  </head>
  <body bgcolor="#253447" text="#979BA0" link="#0000FF" vlink="#800080" topmargin="0" leftmargin="0">

<!--$begin exclude$-->
    <div id="centerwrapper">
      <div id="root" style="position:absolute;width:1000px;height:985px;">
<!--$end exclude$-->
        <div id="e0" style="position:absolute;left:1;top:0;width:998;height:78;"><!--$img %ImageAssetImpl:/images/generic_dusk_header.jpg$--><img src="sitebuilder/images/generic_dusk_header-998x78.jpg" width="998" height="78" alt=""></div>        <div id="e1" style="position:absolute;left:1;top:78;width:998;height:44;"><img src="images/generic_dusk_search_bar_background_tile.gif" width="998" height="44" alt=""></div>        <div id="e2" style="position:absolute;left:150;top:25;width:155;height:41;"><span class="text"><font color="#D4A84B" size="6"><span style="font-size:30px;line-height:35px;">Instructors<br/></span></font></span>        </div>
        <div id="e3" style="position:absolute;left:11;top:198;width:129;height:270;"><!--$navbar 
name=navbar.nav
assetID=%NavbarAsset:/navigation_bars/navbar.nav
$--><!--$begin exclude$--><table border="0" cellspacing="0" cellpadding="0"><tr><td><a href="index.html"><img name="i4" src="sitebuilder/images/navbar-0-inactive-77129.png" border="0" width="129" height="30" alt=""/></a></td></tr><tr><td><a href="news.html"><img name="i5" src="sitebuilder/images/navbar-1-inactive-77285.png" border="0" width="129" height="30" alt=""/></a></td></tr><tr><td><a href="instructors.html" onMouseOver="document.images['i6'].src='sitebuilder/images/navbar-2-mouseOver-58579.png'" onMouseOut="document.images['i6'].src='sitebuilder/images/navbar-2-active-77363.png'"><img name="i6" src="sitebuilder/images/navbar-2-active-77363.png" width="129" height="30" border="0" alt=""/></a></td></tr><tr><td><a href="classes.html" onMouseOver="document.images['i7'].src='sitebuilder/images/navbar-3-mouseOver-58610.png'" onMouseOut="document.images['i7'].src='sitebuilder/images/navbar-3-inactive-77410.png'"><img name="i7" src="sitebuilder/images/navbar-3-inactive-77410.png" border="0" width="129" height="30" alt=""/></a></td></tr><tr><td><a href="DojoRules-Introduction.html" onMouseOver="document.images['i8'].src='sitebuilder/images/navbar-5-mouseOver-34128.png'" onMouseOut="document.images['i8'].src='sitebuilder/images/navbar-5-inactive-34097.png'"><img name="i8" src="sitebuilder/images/navbar-5-inactive-34097.png" border="0" width="129" height="30" alt=""/></a></td></tr><tr><td><a href="events.html" onMouseOver="document.images['i9'].src='sitebuilder/images/navbar-6-mouseOver-76292.png'" onMouseOut="document.images['i9'].src='sitebuilder/images/navbar-6-inactive-76261.png'"><img name="i9" src="sitebuilder/images/navbar-6-inactive-76261.png" border="0" width="129" height="30" alt=""/></a></td></tr><tr><td><a href="Photos.html" onMouseOver="document.images['i10'].src='sitebuilder/images/navbar-7-mouseOver-03618.png'" onMouseOut="document.images['i10'].src='sitebuilder/images/navbar-7-inactive-03586.png'"><img name="i10" src="sitebuilder/images/navbar-7-inactive-03586.png" border="0" width="129" height="30" alt=""/></a></td></tr><tr><td><a href="links.html" onMouseOver="document.images['i11'].src='sitebuilder/images/navbar-8-mouseOver-60165.png'" onMouseOut="document.images['i11'].src='sitebuilder/images/navbar-8-inactive-60149.png'"><img name="i11" src="sitebuilder/images/navbar-8-inactive-60149.png" border="0" width="129" height="30" alt=""/></a></td></tr><tr><td><a href="contactus.html" onMouseOver="document.images['i12'].src='sitebuilder/images/navbar-9-mouseOver-62733.png'" onMouseOut="document.images['i12'].src='sitebuilder/images/navbar-9-inactive-62714.png'"><img name="i12" src="sitebuilder/images/navbar-9-inactive-62714.png" border="0" width="129" height="30" alt=""/></a></td></tr></table><!--$end exclude$-->        </div>
        <div id="e13" style="position:absolute;left:164;top:144;width:576;height:189;"><span class="text"><span style="font-size:12px;line-height:15px;">Steven W. Majors was born and raised in Trenton, NJ. He began his Shotokan training in 1985 with John <br/>Harders. In addition to Shotokan, Mr. Majors holds a brown belt in Judo and has also trained in Mo Duk <br/>Kwon, Tae Kwon Do, and Tai Chi Chuan. In August, 1994, he began his studies in the International <br/>Shotokan Karate Federation (ISKF). Mr. Majors has completed the ISKF Instructor Training Program and <br/>is a certified instructor, examiner and judge. He continues to train periodically with Master Okazaki in <br/>Philadelphia. Currently, he is teaching Shotokan at two Fairfax County community recreation centers <br/>under a cooperative program with the Fairfax County Recreation Department. Mr. Majors holds a Master of <br/>Arts degree from C. W. Post Center of Long Island University, a Bachelor of Fine Arts from Virginia <br/>Commonwealth University, and an Associate of Arts from Mercer County Community College in Trenton, <br/>NJ. He was director of the Torpedo Factory Art Center in Alexandria, VA for eight years and Curator of the <br/>Washington County Museum of Fine Arts in Hagerstown, MD for nearly four years. An artist as well, his <br/>work has been exhibited in New York, New Jersey, Pennsylvania, Maryland, Virginia, and West Virginia.<br/></span></span>        </div>
        <div id="e14" style="position:absolute;left:382;top:390;width:313;height:90;"><span class="text"><span style="font-size:12px;line-height:15px;">Eileen Chotiner began training in Shotokan in 1993 and <br/>has been a member of the ISKF since 1994. She assists <br/>with instruction at all locations and also trains <br/>periodically with Master Okazaki, as well as other special <br/>ISKF trainings and tournaments. She earned her 3rd <br/>Dan in May 2006.<br/></span></span>        </div>
        <div id="e15" style="position:absolute;left:775;top:129;width:203;height:302;"><img src="images/InstructorSteveMajors.gif" width="203" height="302" alt=""></div>        <div id="e16" style="position:absolute;left:774;top:445;width:215;height:30;"><span class="text"><b><font color="#D4A84B"><span style="font-size:12px;line-height:15px;">Instructor Steven W. Majors, 4th Dan<br/></span></font></b></span>        </div>
        <div id="e17" style="position:absolute;left:162;top:350;width:195;height:306;"><img src="images/chotinerkataweb.gif" width="195" height="306" alt=""></div>        <div id="e18" style="position:absolute;left:162;top:671;width:195;height:45;"><span class="text"><b><font color="#D4A84B"><span style="font-size:12px;line-height:15px;">Assistant Instructor<br>Eileen &nbsp;Chotiner, 3rd Dan<br></span></font></b><font color="#D4A84B"><span style="font-size:12px;line-height:15px;">Photo by Michael Katayanagi<br/></span></font></span>        </div>
        <div id="e19" style="position:absolute;left:150;top:80;width:446;height:28;"><span class="text"><font color="#D4A84B" size="4"><span style="font-size:18px;line-height:22px;">Dominion Shotokan Karate Club, LLC<br/></span></font></span>        </div>
        <div id="e20" style="position:absolute;left:459;top:523;width:202;height:318;"><!--$img %ImageAssetImpl:/images/DSC_00402.JPG$--><img src="sitebuilder/images/DSC_00402-202x318.jpg" width="202" height="318" alt=""></div>        <div id="e21" style="position:absolute;left:459;top:859;width:194;height:45;"><span class="text"><b><font color="#D4A84B"><span style="font-size:12px;line-height:15px;">Shaun Lee , 3rd Dan<br></span></font></b><font color="#D4A84B"><span style="font-size:12px;line-height:15px;">ISKF Instructor Trainee<br/></span></font></span>        </div>
        <div id="e22" style="position:absolute;left:687;top:554;width:297;height:112;"><span class="text"><span style="font-size:12px;line-height:15px;">Shaun Lee began training with Sensei Steve Pohle at <br/>William and Mary and has continued training with the <br/>ISKF since 2001, reaching the rank of sandan. &nbsp;He <br/>has studied under numerous instructors in Michigan <br/>and Virginia as well as through the ISKF 's Master and <br/>Fall Camps, clinics, and tournaments. &nbsp;He is currently <br/>enrolled in the ISKF Instructor Trainee program.<br/></span></span>        </div>
        <div id="e23" style="position:absolute;left:1;top:921;width:996;height:44;"><img src="images/generic_dusk_footer.gif" width="996" height="44" alt=""></div>        <div id="e24" style="position:absolute;left:1;top:0;width:125;height:124;"><img src="images/site_logo_-_125x125_-_transparent.gif" width="125" height="124" alt=""></div>        <div id="e25" style="position:absolute;left:343;top:934;width:308;height:18;"><span class="text"><font color="#D4A84B"><span style="font-size:12px;line-height:15px;">Copyright &#169; Dominion Shotokan Karate Club, LLC 2010<br/></span></font></span>        </div>
<!--$begin exclude$-->
      </div>
    </div>
<!--$end exclude$-->
<!--$begin exclude$--><div style="position:absolute;left:50;top:50;background:white"><font color=black>This file is not intended to be viewed directly using a web browser.  To create a viewable file, use the <b>Preview in Browser</b> or <b>Publish to Yahoo! Web Hosting</b> commands from within Yahoo! SiteBuilder.</font></div><!--$end exclude$-->
  </body>
</html>
